- name: Configuring Catalogue server
  become: yes
  hosts: catalogue
  tasks:
    - name: Disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Create roboshop 
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app

    - name: Create application directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download catalogue application
      ansible.builtin.get_url:
        url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
        dest: /tmp/catalogue.zip

    - name: Unzip application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes  # This means file already exists in this particular server.

    - name: Install nodejs application dependencies
      community.general.npm:
        path: /app

    - name: Copy catalogue systemd service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: systemctl daemon-reload
      ansible.builtin.systemd_service:
        name: catalogue
        daemon_reload: yes
    
    - name: Start & Enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: Copy mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present
    
    - name: Check products are loaded or not
      ansible.builtin.command: mongosh --host mongodb.easydevops.fun --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print catalogue output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    - name: Load products
      ansible.builtin.shell: mongosh -- host mongodb.easydevops.fun < /app/db/master-data.js
      when: catalogue_output.stdout | int < 0

      

     

