- name: Configuring Shipping service
  become: yes
  hosts: shipping
  tasks:
    - name: Install maven
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
      loop: 
      - maven
      - mysql

    - name: Create roboshop system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app

    - name: Create application directory
      ansible.builtin.file:
        path: /app
        state: directory
      
    - name: Download Shipping application
      ansible.builtin.get_url:
        url: "https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip"
        dest: /tmp/shipping.zip
      
    - name: Unzip application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes  # This means file already exists in this particular server.

    - name: Install maven dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: Move and rename jar file
      ansible.builtin.command: mv /app/target/shipping-1.0.jar /app/shipping.jar

    - name: Copy Shipping systemd service file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: systemctl daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: yes

    - name: Enable & Start the Shipping service
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: yes

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
      - PyMySQL
      - cryptography

    # - name: Connect to mysql app user
    #   community.mysql.mysql_info:
    #     login_user: shipping
    #     login_password: RoboShop@1
    #     login_host: mysql.easydevops.fun
    #     login_db: cities

    - name: Import the data
      tags:
        import
      community.mysql.mysql_db:
        name: all
        login_user: root
        login_password: RoboShop@1
        login_host: mysql.easydevops.fun
        state: import
        target: "{{ item }}"
      loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql
      - /app/db/master-data.sql

    - name: Restart Shipping service
      ansible.builtin.service:
        name: shipping
        state: restarted
